// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqg5dkqY30Pm99Oot3J3yg6T2PwVUbjvQ',
    appId: '1:868394378084:web:f4ba614778f9e07d4cd071',
    messagingSenderId: '868394378084',
    projectId: 'taxi-hexa-9d436',
    authDomain: 'taxi-hexa-9d436.firebaseapp.com',
    storageBucket: 'taxi-hexa-9d436.appspot.com',
    measurementId: 'G-RSB2LZMDKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXow-1RkkwMbYyXi3N6wnCGgHIX7_QgnE',
    appId: '1:868394378084:android:4c0d69c716c8dd444cd071',
    messagingSenderId: '868394378084',
    projectId: 'taxi-hexa-9d436',
    storageBucket: 'taxi-hexa-9d436.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm4WXXejASXMeHB5E-d3J2v8kUGn0V1As',
    appId: '1:868394378084:ios:e9bf90219b46f0f24cd071',
    messagingSenderId: '868394378084',
    projectId: 'taxi-hexa-9d436',
    storageBucket: 'taxi-hexa-9d436.appspot.com',
    iosClientId: '868394378084-c2lgcu07sfa8oec2vc9kg9jv7t57fvco.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxiHexa',
  );
}
